//! GPU kernel host-side dispatch functions.
//!
//! Each submodule implements dispatch for a specific kernel family.

pub mod argmax;
pub mod argsort;
pub mod compute_g_beta;
pub mod copy;
pub mod cumsum;
pub mod deepseek_activation_quant;
pub mod deepseek_compressor;
pub mod deepseek_hyper_connection;
pub mod deepseek_indexer;
pub mod deepseek_moe_activation;
pub mod deepseek_moe_routing;
pub mod deepseek_sparse_attention;
pub mod deepseek_sparse_prefill_mask;
pub mod deepseek_tail_rope;
pub mod dense_bf16_auto;
mod dense_bf16_calibration;
mod dense_bf16_contract;
pub mod dense_gemm;
pub mod dense_gemv_bf16;
pub mod dense_mm_bf16;
mod dense_mm_capability;
pub mod dense_mm_f16;
pub mod dense_mm_f32_f32;
#[cfg(test)]
mod dense_mm_fallback_tests;
mod dense_q4_acceptance;
pub mod dense_q4_auto;
mod dense_q4_calibration;
pub mod dequant_to_f16;
pub mod elementwise;
pub mod embedding;
pub mod embedding_dense;
pub mod embedding_kquant;
pub mod embedding_q2_k;
pub mod embedding_q4_0;
pub mod embedding_q4_k;
pub mod embedding_q8_0;
pub mod encode_helpers;
pub mod flash_attn_prefill;
pub mod flash_attn_prefill_blk;
pub mod flash_attn_prefill_d512;
pub mod flash_attn_prefill_mask;
pub mod flash_attn_train;
pub mod flash_attn_vec;
pub mod flash_attn_vec_tq;
pub mod fused_dual_proj_q4_0;
pub mod fused_gate_up_silu_iq4_nl;
#[allow(non_snake_case)]
pub mod fused_gate_up_silu_q4_K;
#[allow(non_snake_case)]
pub mod fused_gate_up_silu_q5_K;
#[allow(non_snake_case)]
pub mod fused_gate_up_silu_q6_K;
pub mod fused_gate_up_silu_q8_0;
pub mod fused_head_norm_rope;
pub mod fused_norm_add;
pub mod fused_residual_norm;
pub mod gather;
pub mod gather_bench;
pub mod gelu;
pub mod gpu_sample;
pub mod hadamard;
pub mod hadamard_quantize_kv;
pub mod kv_cache_copy;
pub mod l2_norm;
pub mod log_elementwise;
pub mod moe_dispatch;
pub mod moe_gate;
pub mod moe_mm_id_map0;
pub mod moe_softmax_topk;
pub mod moe_weighted_reduce;
pub mod mul_mv_ext;
pub mod q_gate_deinterleave;
pub mod qkv_split;
pub mod quantized_matmul;
pub mod quantized_matmul_ggml;
pub mod quantized_matmul_id;
pub mod quantized_matmul_id_ggml;
pub mod repeat_tiled;
pub mod rms_norm;
pub mod rope;
mod rope_freqs;
pub mod rope_multi;
pub mod rope_train;
pub mod row_sum;
pub mod scale_mask_softmax;
pub mod sigmoid_mul;
pub mod silu_mul;
pub mod ssm_norm_gate;
pub mod top_k;
pub mod vision_2d_rope;
// ADR-037 Phase E1.1 (2026-05-22) — EAGLE-3 + dynamic tree port.
pub mod adam_update;
pub mod chunk_gated_delta_rule;
pub mod chunk_gated_delta_rule_bank_split;
pub mod chunk_gated_delta_rule_tri_solve_invert;
pub mod conv1d_depthwise_causal;
pub mod divide_elementwise;
pub mod embedding_autograd;
pub mod exp_elementwise;
pub mod flash_attn_vec_hybrid;
pub mod flash_attn_vec_peer_port_f16;
pub mod flash_attn_vec_reduce_tq_hb_undo;
pub mod flash_attn_vec_tq_hb;
pub mod fwht_standalone;
pub mod gated_delta_net;
pub mod gated_delta_net_chunk;
pub mod gated_delta_net_chunk_o;
pub mod gated_delta_net_decode;
pub mod gated_delta_net_kkt;
pub mod gated_delta_net_recompute_wu;
pub mod outer_product;
pub mod qdq_affine;
pub mod qdq_legacy;
pub mod qmm_affine;
pub mod rms_norm_backward;
pub mod sdpa;
pub mod sdpa_decode;
pub mod sdpa_sliding;
pub mod silu_backward;
pub mod slice_concat_2d;
pub mod softcap;
pub mod softmax;
pub mod softmax_backward;
pub mod softmax_sample;
pub mod sqrt_elementwise;
pub mod ssm_conv;
pub mod take_along_axis;
pub mod tq_dequantize_kv;
pub mod transpose;
pub mod tree_attention;
pub mod tri_solve;
// ADR-021 Qwen3-VL ViT prelude GPU port (5 new kernels):
pub mod add_bias_row_2d;
pub mod bilinear_resize_2d;
pub mod block_merge_2x2;
pub mod feature_concat;
pub mod im2col_2d_3ch;
